[package]
name = "radiswap-adapter"
version.workspace = true
edition.workspace = true
description = "Defines the adapter for Radiswap."

[dependencies]
sbor = { workspace = true }
scrypto = { workspace = true }
radix-engine-interface = { workspace = true }
scrypto-interface = { workspace = true }
common = { workspace = true }
ports-interface = { workspace = true }

[features]
default = []
test = []

manifest-builder-stubs = []

[lib]
crate-type = ["cdylib", "lib"]

[lints]
workspace = true
