[package]
name = "fidenaro"
version.workspace = true
edition.workspace = true
description = "The implementation of the Fidenaro protocol"

[dependencies]
sbor = { workspace = true }
scrypto = { workspace = true }
ports-interface = { workspace = true }

[dev-dependencies]
scrypto-test = { workspace = true }
user-factory = { path = "../user-factory" }

[features]
default = []

[lib]
crate-type = ["cdylib", "lib"]

[lints]
workspace = true
