# Use an official Rust image as the base
FROM rust:latest

# Install system dependencies
RUN apt-get update && \
    apt-get install -y clang build-essential llvm && \
    rm -rf /var/lib/apt/lists/*

# Set up environment for Rust
RUN rustup target add wasm32-unknown-unknown

# Install radix-clis
RUN cargo install --force radix-clis

# Set working directory
WORKDIR /usr/src/app
