[package]
name = "ociswap-v2-adapter"
version.workspace = true
edition.workspace = true
description = "Defines the adapter for Ociswap"

[dependencies]
sbor = { workspace = true }
scrypto = { workspace = true }
radix-engine-interface = { workspace = true }
radix-common = { workspace = true }
radix-transactions = { workspace = true, optional = true }

common = { workspace = true }
scrypto-interface = { workspace = true }
ports-interface = { workspace = true }


[features]
default = []
test = []

manifest-builder-stubs = ["dep:radix-transactions"]

[lib]
crate-type = ["cdylib", "lib"]

[lints]
workspace = true
