[package]
name = "trade-vault"
version.workspace = true
edition.workspace = true
description = "The implementation of the trade vault"
build = "build.rs"

[dependencies]
sbor = { workspace = true }
scrypto = { workspace = true }
ports-interface = { path = "../../libraries/ports-interface" }

[dev-dependencies]
scrypto-test = { workspace = true }
user-factory = { path = "../user-factory" }

[features]
default = []
test = []

[lib]
crate-type = ["cdylib", "lib"]

[lints]
workspace = true
